In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/raw/application_train.csv")

print(df["TARGET"].value_counts(normalize=True))

print(df.dtypes.value_counts())

TARGET
0    0.919271
1    0.080729
Name: proportion, dtype: float64
float64    65
int64      41
str        16
Name: count, dtype: int64

In [6]:
missing = df.isnull().mean().sort_values(ascending=False)
print(missing.head(50))

COMMONAREA_AVG                  0.698723
COMMONAREA_MODE                 0.698723
COMMONAREA_MEDI                 0.698723
NONLIVINGAPARTMENTS_MEDI        0.694330
NONLIVINGAPARTMENTS_MODE        0.694330
NONLIVINGAPARTMENTS_AVG         0.694330
FONDKAPREMONT_MODE              0.683862
LIVINGAPARTMENTS_AVG            0.683550
LIVINGAPARTMENTS_MEDI           0.683550
LIVINGAPARTMENTS_MODE           0.683550
FLOORSMIN_MODE                  0.678486
FLOORSMIN_AVG                   0.678486
FLOORSMIN_MEDI                  0.678486
YEARS_BUILD_AVG                 0.664978
YEARS_BUILD_MODE                0.664978
YEARS_BUILD_MEDI                0.664978
OWN_CAR_AGE                     0.659908
LANDAREA_MEDI                   0.593767
LANDAREA_AVG                    0.593767
LANDAREA_MODE                   0.593767
BASEMENTAREA_MODE               0.585160
BASEMENTAREA_MEDI               0.585160
BASEMENTAREA_AVG                0.585160
EXT_SOURCE_1                    0.563811
NONLIVINGAREA_MODE              0.551792
NONLIVINGAREA_AVG               0.551792
NONLIVINGAREA_MEDI              0.551792
ELEVATORS_AVG                   0.532960
ELEVATORS_MEDI                  0.532960
ELEVATORS_MODE                  0.532960
WALLSMATERIAL_MODE              0.508408
APARTMENTS_AVG                  0.507497
APARTMENTS_MEDI                 0.507497
APARTMENTS_MODE                 0.507497
ENTRANCES_MODE                  0.503488
ENTRANCES_MEDI                  0.503488
ENTRANCES_AVG                   0.503488
LIVINGAREA_AVG                  0.501933
LIVINGAREA_MEDI                 0.501933
LIVINGAREA_MODE                 0.501933
HOUSETYPE_MODE                  0.501761
FLOORSMAX_MODE                  0.497608
FLOORSMAX_AVG                   0.497608
FLOORSMAX_MEDI                  0.497608
YEARS_BEGINEXPLUATATION_MODE    0.487810
YEARS_BEGINEXPLUATATION_MEDI    0.487810
YEARS_BEGINEXPLUATATION_AVG     0.487810
TOTALAREA_MODE                  0.482685
EMERGENCYSTATE_MODE             0.473983
OCCUPATION_TYPE                 0.313455
dtype: float64

In [8]:
cols = ["AMT_INCOME_TOTAL", "AMT_CREDIT", "DAYS_BIRTH", "DAYS_EMPLOYED",
        "EXT_SOURCE_1", "EXT_SOURCE_2", "EXT_SOURCE_3"]

df[cols].describe()

,AMT_INCOME_TOTAL,AMT_CREDIT,DAYS_BIRTH,DAYS_EMPLOYED,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3
count,3.075110e+05,3.075110e+05,307511.000000,307511.000000,134133.000000,3.068510e+05,246546.000000
mean,1.687979e+05,5.990260e+05,-16036.995067,63815.045904,0.502130,5.143927e-01,0.510853
std,2.371231e+05,4.024908e+05,4363.988632,141275.766519,0.211062,1.910602e-01,0.194844
min,2.565000e+04,4.500000e+04,-25229.000000,-17912.000000,0.014568,8.173617e-08,0.000527
25%,1.125000e+05,2.700000e+05,-19682.000000,-2760.000000,0.334007,3.924574e-01,0.370650
50%,1.471500e+05,5.135310e+05,-15750.000000,-1213.000000,0.505998,5.659614e-01,0.535276
75%,2.025000e+05,8.086500e+05,-12413.000000,-289.000000,0.675053,6.636171e-01,0.669057
max,1.170000e+08,4.050000e+06,-7489.000000,365243.000000,0.962693,8.549997e-01,0.896010

In [9]:
df.groupby("TARGET")[["AMT_INCOME_TOTAL", "AMT_CREDIT", "EXT_SOURCE_1", "EXT_SOURCE_2", "EXT_SOURCE_3"]].mean()

,AMT_INCOME_TOTAL,AMT_CREDIT,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3
TARGET,,,,,
0,169077.722266,602648.282002,0.511461,0.523479,0.520969
1,165611.760906,557778.527674,0.386968,0.410935,0.390717

In [10]:
print(df["DAYS_EMPLOYED"].max())
print((df["DAYS_EMPLOYED"] == df["DAYS_EMPLOYED"].max()).sum())

365243
55374